import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const APP_SIGNATURE = "T2P";

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Supabase credentials not configured');
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const { qrData, scannedByWallet } = await req.json();

    if (!qrData) {
      throw new Error('Missing QR data');
    }

    console.log('Verifying QR code, scanned by:', scannedByWallet);

    // Parse the QR data
    let parsedData;
    try {
      parsedData = JSON.parse(qrData);
    } catch {
      // Log the failed scan
      await logScan(supabase, null, scannedByWallet, false, 'Invalid QR format - not JSON');
      return new Response(
        JSON.stringify({
          success: false,
          verified: false,
          error: 'Invalid QR code format',
          reason: 'not_app_qr',
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Verify app signature
    if (parsedData.app !== APP_SIGNATURE) {
      await logScan(supabase, null, scannedByWallet, false, 'QR not from Trash2Pay app');
      return new Response(
        JSON.stringify({
          success: false,
          verified: false,
          error: 'This QR code was not generated by Trash2Pay',
          reason: 'invalid_app_signature',
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const { token, user: qrOwner } = parsedData;

    if (!token || !qrOwner) {
      await logScan(supabase, null, scannedByWallet, false, 'Missing token or user in QR');
      return new Response(
        JSON.stringify({
          success: false,
          verified: false,
          error: 'Invalid QR code data',
          reason: 'missing_fields',
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Look up the QR code in database
    const { data: qrRecord, error: lookupError } = await supabase
      .from('user_qr_codes')
      .select('*')
      .eq('qr_token', token)
      .eq('user_id', qrOwner)
      .maybeSingle();

    if (lookupError) {
      console.error('Database lookup error:', lookupError);
      throw new Error('Failed to verify QR code');
    }

    if (!qrRecord) {
      await logScan(supabase, null, scannedByWallet, false, 'QR code not found in database');
      return new Response(
        JSON.stringify({
          success: false,
          verified: false,
          error: 'QR code not found or has been revoked',
          reason: 'not_found',
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!qrRecord.is_active) {
      await logScan(supabase, qrRecord.id, scannedByWallet, false, 'QR code is deactivated');
      return new Response(
        JSON.stringify({
          success: false,
          verified: false,
          error: 'This QR code has been deactivated',
          reason: 'deactivated',
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // QR code is valid! Update scan count and log success
    await supabase
      .from('user_qr_codes')
      .update({
        scan_count: (qrRecord.scan_count || 0) + 1,
        last_scanned_at: new Date().toISOString(),
      })
      .eq('id', qrRecord.id);

    await logScan(supabase, qrRecord.id, scannedByWallet, true, null);

    console.log('QR code verified successfully for user:', qrOwner);

    return new Response(
      JSON.stringify({
        success: true,
        verified: true,
        qrOwner: qrOwner,
        scanCount: (qrRecord.scan_count || 0) + 1,
        message: 'QR code verified successfully',
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: unknown) {
    console.error('QR verification error:', error);
    const message = error instanceof Error ? error.message : 'An unknown error occurred';
    return new Response(
      JSON.stringify({ error: message, success: false, verified: false }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

async function logScan(
  supabase: any,
  qrCodeId: string | null,
  scannedBy: string | null,
  result: boolean,
  failureReason: string | null
) {
  try {
    await supabase
      .from('qr_scan_logs')
      .insert({
        qr_code_id: qrCodeId,
        scanned_by_user_id: scannedBy,
        verification_result: result,
        failure_reason: failureReason,
      });
  } catch (e) {
    console.error('Failed to log scan:', e);
  }
}
