import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { encodeBase64 } from "https://deno.land/std@0.224.0/encoding/base64.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// App signature to verify QR codes are generated by Trash2Pay
const APP_SIGNATURE = "T2P";
const APP_VERSION = "1";

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Supabase credentials not configured');
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);
    const { walletHandle, userRole } = await req.json();

    if (!walletHandle) {
      throw new Error('Missing walletHandle');
    }

    console.log('Generating QR code for:', walletHandle, 'role:', userRole);

    // Check if user already has an active QR code
    const { data: existingQR } = await supabase
      .from('user_qr_codes')
      .select('*')
      .eq('user_id', walletHandle)
      .eq('is_active', true)
      .maybeSingle();

    if (existingQR) {
      console.log('Returning existing QR code for user');
      return new Response(
        JSON.stringify({
          success: true,
          qrToken: existingQR.qr_token,
          qrData: generateQRData(existingQR.qr_token, walletHandle),
          isExisting: true,
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Generate a unique cryptographic token
    const randomBytes = new Uint8Array(32);
    crypto.getRandomValues(randomBytes);
    const uniqueToken = encodeBase64(randomBytes)
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=/g, '');

    // Create timestamp for additional uniqueness
    const timestamp = Date.now().toString(36);
    
    // Combine elements into final token
    const qrToken = `${APP_SIGNATURE}${APP_VERSION}_${timestamp}_${uniqueToken}`;

    // Store in database
    const { error: insertError } = await supabase
      .from('user_qr_codes')
      .insert({
        user_id: walletHandle,
        qr_token: qrToken,
        is_active: true,
      });

    if (insertError) {
      console.error('Failed to store QR code:', insertError);
      throw new Error('Failed to generate QR code');
    }

    console.log('Successfully generated new QR code');

    return new Response(
      JSON.stringify({
        success: true,
        qrToken: qrToken,
        qrData: generateQRData(qrToken, walletHandle),
        isExisting: false,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: unknown) {
    console.error('QR generation error:', error);
    const message = error instanceof Error ? error.message : 'An unknown error occurred';
    return new Response(
      JSON.stringify({ error: message, success: false }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

function generateQRData(token: string, walletHandle: string): string {
  // Create a structured payload that includes verification data
  const payload = {
    app: APP_SIGNATURE,
    version: APP_VERSION,
    token: token,
    user: walletHandle,
    generated: Date.now(),
  };
  
  // Return as JSON string for QR encoding
  return JSON.stringify(payload);
}
